### ISSUE TITLE
"Unexpected end of string, square brackets do not match" on fish

### ISSUE THREAD

**Issue by ranisalt** [nodenv/nodenv#89] opened 2017-10-16 05:21 UTC
I am having an issue where adding `source (nodenv init -|psub)` as suggested fails on fish.

```
$ source (nodenv init -|psub)
/tmp/.psub.kQ7SIAYaXA (line 9): Unexpected end of string, square brackets do not match
  switch "$command"
^
from sourcing file /tmp/.psub.kQ7SIAYaXA
	called on standard input

source: Error while reading file “/tmp/.psub.kQ7SIAYaXA”
```

Currently running fish 2.6.0 on Arch Linux.

**Comment by jasonkarns** [comment] 2018-11-08 15:12
Looks like a dupe of rbenv/rbenv#973

**Comment by jasonkarns** [comment] 2018-11-08 16:36
Closing since can't repro. Assuming that this is caused by some colorizer for `cat` similar to fish-shell/fish-shell#3868

**Closed by jasonkarns** 2018-11-08 16:36 UTC
