### ISSUE TITLE
Add command to install latest node version

### ISSUE THREAD

**Issue by shaharmor** [nodenv/nodenv#92] opened 2017-11-09 12:47 UTC
Hi,

Node versions are coming out pretty often, and finding out which one is it is cumbersome.
Can you add a `nodenv install latest` that just installs the latest version?

**Comment by jasonkarns** [comment] 2017-11-09 17:58
dupe of https://github.com/nodenv/node-build/issues/145

**Closed by jasonkarns** 2017-11-09 17:58 UTC
