### ISSUE TITLE
Add support for using nodenv in Intellij Idea/Webstorm

### ISSUE THREAD

**Issue by kadaan** [nodenv/nodenv#100] opened 2018-01-12 16:45 UTC
If you add the following to `~/.nodenv/bin/npm-cli.js`, you can get Intellij Idea/Webstorm working with nodenv.

```javascript
#!/usr/bin/env node

const path = require("path");
const { spawn } = require('child_process');
const nodenv_root = path.resolve(__dirname, '..');
process.env.NODENV_ROOT=nodenv_root;
const npm = spawn(`${nodenv_root}/shims/npm`, process.argv.slice(2), { env: process.env });

npm.stdout.on('data', (data) => {
  process.stdout.write(`${data}`);
});

npm.stderr.on('data', (data) => {
  process.stderr.write(`${data}`);
});

```

**Comment by shaharmor** [comment] 2018-08-12 18:29
does this still work? does it also work with npm?

**Comment by jasonkarns** [comment] 2018-08-13 12:40
Nodenv doesn't do anything with npm and indeed, if your nodenv-managed node is in PATH, then that node's npm will also be in PATH and should work out of the box.

My assumption based on the need here to invoke a shim around npm is that your Intellij/Webstorm configuration does not have nodenv's shims in PATH.

Note that the first line from `nodenv init -` (which is typically evaled as part of bashrc), is to prepend nodenv's shims to the PATH:

> export PATH="/usr/local/var/nodenv/shims:${PATH}"

Can you confirm somehow that Intellij's PATH (however it invokes executables), has nodenv's shims in PATH? Based on the workaround above, it seems that is not the case.

**Comment by shaharmor** [comment] 2018-08-13 13:48
I don't know how to check webstorm's PATH, but I managed to get it to work by manually configured the npm package manager path to be `~/.nodenv` (After adding the above code).

<img width="757" alt="screen shot 2018-08-13 at 16 48 36" src="https://user-images.githubusercontent.com/10861920/44035703-c01bd836-9f18-11e8-95b9-1f3194a065d5.png">

**Comment by jasonkarns** [comment] 2018-08-13 13:52
You probably just want the package manager to be ~/.nodenv/shims/npm, right? Not nodenv itself.

**Comment by shaharmor** [comment] 2018-08-13 13:53
If I write `~/.nodenv/shims/npm`, its not working

**Comment by jasonkarns** [comment] 2018-08-13 13:56
Can you cat out the contents of your npm shim?

**Comment by shaharmor** [comment] 2018-08-13 13:58
~~~
~ cat .nodenv/shims/npm
#!/usr/bin/env bash
set -e
[ -n "$NODENV_DEBUG" ] && set -x

program="${0##*/}"
if [ "$program" = "node" ]; then
  for arg; do
    case "$arg" in
    -e* | -- ) break ;;
    */* )
      if [ -f "$arg" ]; then
        export NODENV_DIR="${arg%/*}"
        break
      fi
      ;;
    esac
  done
fi

export NODENV_ROOT="/Users/user/.nodenv"
exec "/usr/local/Cellar/nodenv/1.1.2/libexec/nodenv" exec "$program" "$@"
~~~

```
~ cat .nodenv/bin/npm-cli.js
#!/usr/bin/env node

const path = require("path");
const { spawn } = require('child_process');
const nodenv_root = path.resolve(__dirname, '..');
process.env.NODENV_ROOT=nodenv_root;
const npm = spawn(`${nodenv_root}/shims/npm`, process.argv.slice(2), { env: process.env });

npm.stdout.on('data', (data) => {
  process.stdout.write(`${data}`);
});

npm.stderr.on('data', (data) => {
  process.stderr.write(`${data}`);
});%
```

**Comment by jasonkarns** [comment] 2018-08-13 14:08
I'm assuming the npm-cli hack works because of how npm itself invokes the cli:

https://github.com/npm/cli/blob/latest/bin/npm

But I'm still assuming the only reason npm fails in intellij is that when the npm shim is invoked, it doesn't the right environment, which means nodenv itself and/or nodenv's shims aren't in PATH. That would cause the npm shim to be unable to find the desired node.

I also haven't seen any actual bug report or what the output is for a vanilla installation. (ie without npm-cli hack and with intellij pointing to the correct npm shim)

It would be helpful to see what the error output is and what `node --version` and `npm version` give you from intellij's console.

**Comment by onomated** [comment] 2018-10-30 21:38
I had to resolve directly to the installed node version for this to work for me.  Not ideal since this has to be manually updated for different node versions:
![image](https://user-images.githubusercontent.com/1012979/47752337-2aeed100-dc62-11e8-8a6e-e57712a1127a.png)

**Comment by icfantv** [comment] 2018-11-10 21:17
Has anyone gotten linting (eslint and tslint) to work in WebStorm with this?  I keep getting "Timeout on starting language service process".

**Comment by jasonkarns** [comment] 2019-01-05 08:46
similar issues: https://youtrack.jetbrains.com/issue/WEB-31496

**Comment by jasonkarns** [comment] 2019-01-07 03:32
@kadaan I'm assuming you configured webstorm's "path to package manager" as your $NODENV_ROOT ?

**Comment by jasonkarns** [comment] 2019-01-07 03:52
So far, with Webstorm 2018.3.2, the following seems to work:

in $(nodenv root)/bin/npm-cli.js:
```
#!/usr/bin/env node

const nodenvRoot = require('path').resolve(__dirname, '..')
process.env.NODENV_ROOT = nodenvRoot
process.exitCode = require('child_process')
  .spawnSync(`${nodenvRoot}/shims/npm`, process.argv.slice(2), {stdio: 'inherit'})
  .status
```

Assuming you have webstorm configured to have the package manager be the value of $(nodenv root).

(🎩  to @kadaan for his original variant of this script)

**Comment by jasonkarns** [comment] 2019-01-07 15:48
Discussion with jetbrains: https://intellij-support.jetbrains.com/hc/en-us/requests/1930323

Closing this issue as we've confirmed the problem is a deficiency with jetbrains' configuration.

Have added this issue and the workaround to our FAQ: https://github.com/nodenv/nodenv/wiki/FAQ#jetbrains-webstorm-integration-for-npm

**Closed by jasonkarns** 2019-01-07 15:48 UTC
